const validationRules = [
  {
    entity: "customer",
    config: {
      full_name: true,
      date_of_birth: true,
      nationality_id: true,
      residence_country_id: true,
      id_type: true,
      id_number: true,
      address: true,
      email: true,
      phone_number: true,
      occupation_id: true,
      tax_number_type: true,
      tax_number: true,
      gender: true,
      incorporation_country_id: true,
      incoporated_date: true,
      estimated_monthly_income: true,
      org_reg_number: true,
      industry_id: true,
    },
  },
  {
    entity: "beneficiary",
    config: {
      name: true,
      date_of_birth: true,
      nationality_id: true,
      residence_country_id: true,
      incorporation_country_id: true,
      address: true,
      id_type: true,
      id_number: true,
      tax_number_type: true,
      tax_number: true,
      reg_number: true,
      occupation_id: true,
      industry_id: true,
      email: true,
      phone: true,
      bank_name: true,
      bank_address: true,
      bank_city: true,
      bank_state: true,
      bank_zip: true,
      bank_account_number: true,
      bank_account_name: true,
    },
  },
];

export default validationRules;
